import type { TestRecord } from "./types";

export const redplayTests: TestRecord[] = [
  {
    id: "redplay-test-0001",
    number: "TEST #0001",
    slug: "samurai-vs-diversant-equal-boost",
    status: "draft",
    kind: "class-comparison",
    title: "Самурай vs Диверсант: фарм на равном бусте",
    shortTitle: "Самурай vs Диверсант",
    question: "Стоил ли реролл в Диверсанта того, если экипировка и уровень буста сопоставимы?",
    answer: "В этой серии Диверсант победил на всех трёх локациях, но преимущество менялось от +12,2% до +80,9% XP/ч.",
    summary: "Сравнение двух классов в одинаковой методике: три локации, короткие замеры и пересчёт темпа на час.",
    edition: "essence-special",
    testedAt: null,
    patch: null,
    sampleLabel: "3 локации · по 6 минут на класс",
    contenders: [
      { id: "samurai", name: "Самурай", shortName: "Самурай", accent: "red" },
      { id: "diversant", name: "Диверсант", shortName: "Диверсант", accent: "cyan" },
    ],
    relations: [
      { id: "samurai", type: "class", name: "Самурай" },
      { id: "diversant", type: "class", name: "Диверсант" },
      { id: "captured-earth-fairies", type: "location", name: "Захваченные Феями земли" },
      { id: "land-of-shadows", type: "location", name: "Земля Теней" },
      { id: "elite-rakshasa-barracks", type: "location", name: "Казармы элитных ракшасов" },
    ],
    decisions: [
      { goal: "Выбираю класс для PvE", choice: "Диверсант", reason: "Он дал больше XP и адены во всех сохранённых сравнениях серии." },
      { goal: "Хочу понять размер преимущества", choice: "Смотри по локации", reason: "Разрыв не постоянный: на Земле Теней он заметно меньше, чем у Фей земли." },
    ],
    method: [
      "Сопоставимый буст и экипировка; классовые характеристики после реролла закономерно отличаются.",
      "Каждый класс тестировался по 6 минут на каждой из трёх локаций.",
      "Темп XP/ч и адены/ч получен пересчётом короткого замера ×10.",
      "Сравнивается конкретный персонаж RedPlay, а не теоретический максимум класса.",
    ],
    characterStats: [
      { label: "Физ. атака", values: { samurai: "56 230", diversant: "81 683" } },
      { label: "Урон в PvE", values: { samurai: "97%", diversant: "168%" } },
      { label: "Мощность физ. умений", values: { samurai: "234%", diversant: "277%" } },
      { label: "Шанс крит. атаки", values: { samurai: "137%", diversant: "196%" } },
      { label: "Сила крит. атаки", values: { samurai: "582%", diversant: "634%" } },
      { label: "Снижение отката", values: { samurai: "53,91%", diversant: "52%" } },
    ],
    scenarios: [
      {
        id: "captured-earth-fairies",
        name: "Захваченные Феями земли",
        durationMinutes: 6,
        values: {
          samurai: { xpPerHour: 316.74, adenaPerHour: 1.803 },
          diversant: { xpPerHour: 573, adenaPerHour: 2.745 },
        },
        xpDeltaPercent: 80.9,
        adenaDeltaPercent: 52.2,
        winnerXp: "diversant",
        winnerAdena: "diversant",
      },
      {
        id: "land-of-shadows",
        name: "Земля Теней",
        durationMinutes: 6,
        values: {
          samurai: { xpPerHour: 795.3, adenaPerHour: 2.368 },
          diversant: { xpPerHour: 892, adenaPerHour: 2.699 },
        },
        xpDeltaPercent: 12.2,
        adenaDeltaPercent: 14,
        winnerXp: "diversant",
        winnerAdena: "diversant",
      },
      {
        id: "elite-rakshasa-barracks",
        name: "Казармы элитных ракшасов",
        durationMinutes: 6,
        values: {
          samurai: { xpPerHour: 876, adenaPerHour: null },
          diversant: { xpPerHour: 1349, adenaPerHour: null },
        },
        xpDeltaPercent: 54,
        adenaDeltaPercent: 63.7,
        winnerXp: "diversant",
        winnerAdena: "diversant",
        adenaNote: "В исходной сводке сохранилась разница по адене (+63,7%), но не обе абсолютные величины. Они намеренно не восстановлены догадкой.",
      },
    ],
    measuredFacts: [
      "Диверсант показал больше XP/ч во всех трёх замерах.",
      "Минимальный разрыв по XP/ч зафиксирован на Земле Теней: +12,2%.",
      "Максимальный разрыв по XP/ч зафиксирован у Фей земли: +80,9%.",
      "Среднее преимущество по XP/ч в этой серии — около +41,5%.",
    ],
    interpretation: [
      "Локация влияет на разрыв между классами: одного среднего процента недостаточно для выбора.",
      "Для этого персонажа переход на Диверсанта дал практический прирост фарма, но не одинаковый на любом споте.",
    ],
    limitations: [
      "Шесть минут — короткое окно: случайный спавн, перемещения и единичные простои сильнее влияют на результат.",
      "Дата, сервер и версия патча в исходной сводке не зафиксированы — до публикации их нужно добавить.",
      "«Равный буст» означает сопоставимую экипировку, а не равные итоговые боевые характеристики.",
      "По Казармам не сохранены обе абсолютные величины адены/ч.",
    ],
    applicability: [
      "У вас сопоставимый уровень экипировки и похожий набор усилений.",
      "Вы фармите на одной из протестированных локаций или на споте с похожей плотностью целей.",
      "Вы сравниваете именно скорость PvE-охоты, а не PvP, стоимость реролла или удобство управления.",
    ],
    notProven: [
      "Что Диверсант всегда сильнее Самурая на любой локации.",
      "Что разница сохранится после другого патча или при другом бусте.",
      "Что реролл окупится по адене с учётом его стоимости.",
    ],
    video: { status: "awaiting-url", title: "Равный буст — фарм на 81% выше! Самурай VS Диверсант" },
    evidenceImages: [
      { src: "/redplay-tests/samurai-vs-diversant-stats.png", alt: "Характеристики Самурая и Диверсанта перед тестом", caption: "Исходная таблица характеристик перед сравнением классов." },
      { src: "/redplay-tests/samurai-vs-diversant-fairies.png", alt: "Результаты Самурая и Диверсанта на локации Захваченные Феями земли", caption: "Исходный 6-минутный замер на локации Захваченные Феями земли." },
    ],
    history: [
      { version: "v1", label: "Первичная серия замеров", state: "Текущий черновик" },
      { version: "v2", label: "Повтор после патча", state: "Можно добавить позже без перезаписи v1" },
    ],
  },
  {
    id: "redplay-test-0002",
    number: "TEST #0002",
    slug: "diversant-farm-location-map-1520",
    status: "draft",
    kind: "location-comparison",
    title: "Диверсант: глобальная карта фарма",
    shortTitle: "Диверсант · глобальный тест",
    question: "Куда идти Диверсанту за опытом или аденой — и насколько надёжен каждый замер?",
    answer: "Для разведки лидируют Небесная башня по XP и Крепость Кельбима по адене; длинный тест подтверждает Землю Теней как сильный универсальный серверный выбор.",
    summary: "Единое исследование из трёх серий: карта 16 локаций, точечное сравнение ТОИ 9/11 и длинный контроль Фей земли против Земли Теней.",
    edition: "essence-special",
    testedAt: null,
    patch: null,
    sampleLabel: "3 серии · от 6 минут до 3 ч 4 мин",
    contenders: [
      { id: "giants-well", name: "Пещера Гигантов — колодец", shortName: "Пещера Гигантов — колодец", accent: "red" },
      { id: "giants-spot-2", name: "Пещера Гигантов — 2-й спот", shortName: "Пещера Гигантов — 2-й спот", accent: "cyan" },
      { id: "fire-dragon-swamp", name: "Болото Драконов Огня", shortName: "Болото Драконов Огня", accent: "red" },
      { id: "land-of-shadows", name: "Земля Теней", shortName: "Земля Теней", accent: "cyan" },
      { id: "rakshasa-camp", name: "Лагерь Ракшас", shortName: "Лагерь Ракшас", accent: "red" },
      { id: "bamboo-forest", name: "Бамбуковый лес", shortName: "Бамбуковый лес", accent: "cyan" },
      { id: "fafurion-fortress", name: "Крепость Фафнов", shortName: "Крепость Фафнов", accent: "red" },
      { id: "captured-earth-fairies", name: "Захваченные Феями земли", shortName: "Захваченные Феями земли", accent: "cyan" },
      { id: "ice-monarch-castle", name: "Замок Монарха Льда", shortName: "Замок Монарха Льда", accent: "red" },
      { id: "antaras-lair", name: "Логово Антараса", shortName: "Логово Антараса", accent: "cyan" },
      { id: "pagan-temple", name: "Языческий храм", shortName: "Языческий храм", accent: "red" },
      { id: "toi-9-map", name: "Башня Дерзости — 9 этаж", shortName: "ТОИ 9", accent: "cyan" },
      { id: "toi-10-map", name: "Башня Дерзости — 10 этаж", shortName: "ТОИ 10", accent: "red" },
      { id: "toi-11-map", name: "Башня Дерзости — 11 этаж", shortName: "ТОИ 11", accent: "cyan" },
      { id: "heavenly-tower-93", name: "Небесная башня (93 ур.)", shortName: "Небесная башня (93 ур.)", accent: "red" },
      { id: "kelbim-fortress", name: "Крепость Кельбима (пт.)", shortName: "Крепость Кельбима (пт.)", accent: "cyan" },
    ],
    relations: [
      { id: "diversant", type: "class", name: "Диверсант" },
      { id: "giants-cave", type: "location", name: "Пещера Гигантов" },
      { id: "fire-dragon-swamp", type: "location", name: "Болото Драконов Огня" },
      { id: "land-of-shadows", type: "location", name: "Земля Теней" },
      { id: "toi", type: "location", name: "Башня Дерзости" },
      { id: "heavenly-tower", type: "location", name: "Небесная башня" },
      { id: "kelbim-fortress", type: "location", name: "Крепость Кельбима" },
    ],
    decisions: [
      { goal: "Максимум опыта", choice: "Небесная башня", reason: "2,94 млрд XP/ч — лучший результат всей серии." },
      { goal: "Максимум адены", choice: "Крепость Кельбима", reason: "5,83 млн адены/ч — лучший результат всей серии." },
      { goal: "Стабильный серверный фарм", choice: "Земля Теней", reason: "Длинный замер дал примерно вдвое больше XP, чем Феи земли, при почти равной адене." },
      { goal: "ТОИ: опыт или адена", choice: "ТОИ 11 / ТОИ 9", reason: "В отдельной 10-минутной серии ТОИ 11 выиграл по XP, а ТОИ 9 — по адене." },
    ],
    method: [
      "Один персонаж: Диверсант 92 уровня, 1520 боевой мощи.",
      "Обзорная серия охватывает 16 локаций по 6 минут; опыт и адена пересчитаны в ориентировочный темп за час (×10).",
      "Отдельный 10-минутный замер повторно сравнивает ТОИ 9 и ТОИ 11; он не смешивается с обзорной серией.",
      "Контрольная серия Феи земли vs Земля Теней длилась по 3 часа 4 минуты на каждой локации.",
      "Серии сохранены отдельно: разная длительность и условия означают разный уровень уверенности, а не противоречие данных.",
      "Бамбуковый лес отмечен как непроходимый, а не как нулевой фарм.",
    ],
    scenarios: [
      {
        id: "server-locations",
        name: "Серверные локации",
        durationMinutes: 6,
        contenderIds: ["giants-well", "giants-spot-2", "fire-dragon-swamp", "land-of-shadows", "rakshasa-camp", "bamboo-forest", "fafurion-fortress", "captured-earth-fairies"],
        values: {
          "giants-well": { xpPerHour: 1155, adenaPerHour: 2.65 },
          "giants-spot-2": { xpPerHour: 1650, adenaPerHour: 2.71 },
          "fire-dragon-swamp": { xpPerHour: 1893, adenaPerHour: 1.35 },
          "land-of-shadows": { xpPerHour: 890, adenaPerHour: 2.7 },
          "rakshasa-camp": { xpPerHour: 1340, adenaPerHour: 2.33 },
          "bamboo-forest": { xpPerHour: null, adenaPerHour: null },
          "fafurion-fortress": { xpPerHour: 540, adenaPerHour: 2.64 },
          "captured-earth-fairies": { xpPerHour: 570, adenaPerHour: 2.74 },
        },
        unavailableReason: { "bamboo-forest": "Не выживает" },
        xpDeltaPercent: 14.7,
        adenaDeltaPercent: 1.1,
        winnerXp: "fire-dragon-swamp",
        winnerAdena: "captured-earth-fairies",
        xpNote: "Лидер по XP опережает второй спот Пещеры Гигантов примерно на 14,7%.",
        adenaNote: "Лидеры по адене почти равны: Феи земли опережают второй спот Пещеры Гигантов примерно на 1,1%.",
      },
      {
        id: "cross-server-locations",
        name: "Межсерверные локации",
        durationMinutes: 6,
        contenderIds: ["ice-monarch-castle", "antaras-lair", "pagan-temple", "toi-9-map", "toi-10-map", "toi-11-map", "heavenly-tower-93", "kelbim-fortress"],
        values: {
          "ice-monarch-castle": { xpPerHour: 1060, adenaPerHour: 3.78 },
          "antaras-lair": { xpPerHour: 850, adenaPerHour: 3.17 },
          "pagan-temple": { xpPerHour: 790, adenaPerHour: 4.67 },
          "toi-9-map": { xpPerHour: 1530, adenaPerHour: 2.94 },
          "toi-10-map": { xpPerHour: 1690, adenaPerHour: 1.77 },
          "toi-11-map": { xpPerHour: 1510, adenaPerHour: 1.81 },
          "heavenly-tower-93": { xpPerHour: 2940, adenaPerHour: 3.92 },
          "kelbim-fortress": { xpPerHour: 1500, adenaPerHour: 5.83 },
        },
        xpDeltaPercent: 74,
        adenaDeltaPercent: 24.8,
        winnerXp: "heavenly-tower-93",
        winnerAdena: "kelbim-fortress",
        xpNote: "Небесная башня опережает второй результат межсервера примерно на 74%.",
        adenaNote: "Крепость Кельбима опережает Языческий храм примерно на 24,8%.",
      },
      {
        id: "toi-9-vs-toi-11-control",
        name: "Точечная серия: ТОИ 9 vs ТОИ 11",
        durationMinutes: 10,
        contenderIds: ["toi-9-map", "toi-11-map"],
        values: {
          "toi-9-map": { xpPerHour: 1733, adenaPerHour: 2.69 },
          "toi-11-map": { xpPerHour: 1975, adenaPerHour: 2.209 },
        },
        xpDeltaPercent: 14,
        adenaDeltaPercent: 22,
        winnerXp: "toi-11-map",
        winnerAdena: "toi-9-map",
        xpNote: "Это отдельная 10-минутная серия: ТОИ 11 дал примерно на 14% больше XP.",
        adenaNote: "В этой же серии ТОИ 9 дал примерно на 22% больше валовой адены.",
      },
      {
        id: "earth-fairies-vs-land-of-shadows-long",
        name: "Контрольная серия: Феи земли vs Земля Теней",
        durationMinutes: 184,
        contenderIds: ["captured-earth-fairies", "land-of-shadows"],
        values: {
          "captured-earth-fairies": { xpPerHour: 480.5, adenaPerHour: 2.64 },
          "land-of-shadows": { xpPerHour: 964.4, adenaPerHour: 2.7 },
        },
        xpDeltaPercent: 100.7,
        adenaDeltaPercent: 2.3,
        winnerXp: "land-of-shadows",
        winnerAdena: "land-of-shadows",
        xpNote: "Одинаковые замеры по 3 ч 4 мин: Земля Теней дала примерно вдвое больше опыта.",
        adenaNote: "Разница по адене составила лишь 2,3%, поэтому практический выбор определяется опытом и условиями спота.",
      },
    ],
    measuredFacts: [
      "Небесная башня — максимальный результат по опыту: 2,94 млрд/ч.",
      "Крепость Кельбима — максимальный результат по адене: 5,83 млн/ч.",
      "Среди серверных зон Болото Драконов Огня лидирует по опыту, а Феи земли — по адене.",
      "В Бамбуковом лесу персонаж не выживает; эта зона не должна участвовать в числовом рейтинге.",
      "В отдельной 10-минутной серии ТОИ 11 выиграл по опыту, а ТОИ 9 — по адене.",
      "В длинной серии Земля Теней дала +100,7% XP при разнице по адене всего 2,3% относительно Фей земли.",
    ],
    interpretation: [
      "Лучший спот по опыту почти нигде не является лучшим по адене — цель охоты нужно выбирать заранее.",
      "Межсервер открывает более высокие максимумы, но таблица не учитывает доступность зоны, конкуренцию и групповую организацию.",
      "Разница между двумя спотами одной локации может быть значительной: Пещера Гигантов — наглядный пример.",
      "Для регулярного серверного фарма Земля Теней выглядит сильнее Фей земли: длинный замер почти убирает компромисс между опытом и аденой.",
    ],
    limitations: [
      "Обзорные 6 минут и точечные 10 минут показывают темп, а не гарантированную часовую доходность.",
      "Дата, сервер и версия патча на изображениях не указаны.",
      "Крепость Кельбима отмечена как групповая зона; её нельзя напрямую сравнивать по удобству с одиночными спотами.",
      "Валовая адена не учитывает расходники и редкий дроп.",
    ],
    applicability: [
      "Ваш Диверсант близок к 92 уровню и 1520 боевой мощи.",
      "Вы способны стабильно выживать и держать похожий маршрут на выбранном споте.",
      "Вы сравниваете регулярный опыт и валовую адену, а не редкий дроп или PvP-риски.",
    ],
    notProven: [
      "Что лидер таблицы останется лидером при другом уровне или боевой мощи.",
      "Что межсерверная зона будет доступна без конкуренции.",
      "Что пересчёт короткого окна повторится на длинной дистанции; длинная серия подтверждает только две конкретные локации.",
    ],
    video: { status: "awaiting-url", title: "Фарм Диверсанта: серверные и межсерверные локации" },
    evidenceImages: [
      { src: "/redplay-tests/farm-diversant-all-locations-detailed.png", alt: "Подробное сравнение фарма Диверсанта на серверных и межсерверных локациях", caption: "Первичная таблица: фактические значения за 6 минут и ориентировочный пересчёт на час." },
      { src: "/redplay-tests/farm-diversant-all-locations.png", alt: "Сравнение фарма Диверсанта на серверных и межсерверных локациях", caption: "Визуальная сводка пользователя: 1520 боевой мощи, 92 уровень, оценка по 6-минутному замеру." },
      { src: "/redplay-tests/diversant-fairies-vs-shadows-long.png", alt: "Длинное сравнение фарма Диверсанта у Фей земли и в Земле Теней", caption: "Контрольная серия пользователя: одинаковые замеры по 3 часа 4 минуты.", width: 1080, height: 1350 },
    ],
    history: [
      { version: "Серия A", label: "Карта из 16 локаций · по 6 минут", state: "Обзорный замер" },
      { version: "Серия B", label: "ТОИ 9 vs ТОИ 11 · по 10 минут", state: "Точечный замер" },
      { version: "Серия C", label: "Феи земли vs Земля Теней · по 3 ч 4 мин", state: "Длинный контроль" },
      { version: "Следующая", label: "Повтор на новом уровне или патче", state: "Добавится без перезаписи серий" },
    ],
  },
];

export const redplayTestAliases: Record<string, string> = {
  "diversant-toi-9-vs-toi-11": "diversant-farm-location-map-1520",
  "diversant-earth-fairies-vs-land-of-shadows-long-test": "diversant-farm-location-map-1520",
};

export function getRedplayTest(slug: string) {
  const resolvedSlug = redplayTestAliases[slug] || slug;
  return redplayTests.find((test) => test.slug === resolvedSlug) || null;
}
